### ISSUE TITLE
Error - NoneType object is not iterable ?

### ISSUE THREAD

**Issue by avnish80** [vmware/vcd-cli#377]
<img width="552" alt="error" src="https://user-images.githubusercontent.com/47804703/53471060-82bf0c80-3a89-11e9-840e-339f216bf0ec.png">

**Comment by onthax** [comment]
I am getting the same issue.
also using the -i flag only

**Comment by frdmn** [comment]
For anyone who ran into this: check if you have an empty key in your `~/.vcd-cli/profiles.yaml` configuration file and remove that accordingly. In our case, the offending line was a `profiles:` key at line 4 without any content. The corrected version looks like this:

```yml
active: default
extensions:
- container_service_extension.client.cse
```
